"""
Django settings for wakeword project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)m%q*kivs8=8ud@yi_a3kv142@l20#gl)q&_4gc$-zz7u)cd3l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wakeword.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wakeword.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

# Model Configuration
MODEL_CONFIG = {
    'WAKEWORD': {
        'PATH': os.path.join(BASE_DIR, 'detection/models/wakeword.onnx'),
        'THRESHOLD': 0.7,  # Confidence threshold
        'SAMPLE_RATE': 16000,
        'CHUNK_SIZE': 24000  # 1.5 seconds of audio
    },
    'PANIC': {
        'PATH': os.path.join(BASE_DIR, 'detection/models/calmalert_model.pt'),
        'THRESHOLD': 0.65,
        'SAMPLE_RATE': 16000,
        'MAX_LENGTH': 2.4  # Seconds
    }
}

# Audio Processing
AUDIO_CONFIG = {
    'MAX_FILE_SIZE': 5242880,  # 5MB
    'ALLOWED_TYPES': ['audio/wav', 'audio/x-wav'],
    'TEMP_DIR': os.path.join(BASE_DIR, 'temp_audio')
}

# WebSocket Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    }
}

# Emergency Alerts
EMERGENCY_CONFIG = {
    'TWILIO': {
        'ACCOUNT_SID': os.getenv('TWILIO_SID'),
        'AUTH_TOKEN': os.getenv('TWILIO_TOKEN'),
        'FROM_NUMBER': '+1234567890'
    },
    'CONTACTS': [
        '+15551234567',
        'admin@example.com'
    ]
}

# Create temp directory on startup
os.makedirs(AUDIO_CONFIG['TEMP_DIR'], exist_ok=True)